const routes = {
  '/': { label: 'Home', title: 'Banking without borders.', render: homePage },
  '/knowledge': { label: 'Knowledge', title: 'Knowledge for a global life.', render: knowledgePage },
  '/community': { label: 'Community', title: 'Build a better financial future together.', render: communityPage },
  '/membership': { label: 'Membership', title: 'A clearer way to manage money.', render: membershipPage },
  '/resources': { label: 'Resources', title: 'Practical tools for every move.', render: resourcesPage },
  '/about': { label: 'About', title: 'Built for a connected world.', render: aboutPage },
  '/guidelines': { label: 'Guidelines', title: 'A safer, more useful community.', render: guidelinesPage },
  '/contact': { label: 'Contact', title: 'Let’s start a conversation.', render: contactPage },
  '/login': { label: 'Log in', title: 'Welcome back.', render: authPage },
  '/register': { label: 'Register', title: 'Start your global journey.', render: authPage },
  '/dashboard': { label: 'Dashboard', title: 'Your global overview.', render: dashboardPage }
};

const app = document.querySelector('#app');
const clockZones = [['London', 'Europe/London'], ['New York', 'America/New_York'], ['Singapore', 'Asia/Singapore']];
const icon = { arrow: '↗', globe: '◎', shield: '◇', chart: '⌁', book: '▤', people: '◌' };

function navigate(path) { window.history.pushState({}, '', path); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function link(path, text, className = '') { return `<a class="${className}" href="${path}" data-route>${text}</a>`; }
function card(eyebrow, heading, text, action = '') { return `<article class="feature-card"><span class="card-icon">${eyebrow}</span><h3>${heading}</h3><p>${text}</p>${action}</article>`; }
function render() {
  const path = window.location.pathname === '' ? '/' : window.location.pathname;
  const route = routes[path] || routes['/'];
  app.innerHTML = `${shell(route, route.render())}`;
  document.title = `${route.title} | GlobalBank`;
  document.querySelectorAll('[data-route]').forEach(element => element.addEventListener('click', event => { event.preventDefault(); navigate(element.getAttribute('href')); }));
  document.querySelector('#menu-toggle')?.addEventListener('click', () => document.querySelector('.site-nav').classList.toggle('open'));
  document.querySelector('#year').textContent = new Date().getFullYear();
  updateClocks();
  if (path === '/dashboard') loadClock();
}
function shell(route, content) {
  const primaryLinks = ['/knowledge', '/community', '/membership', '/resources'];
  return `<header class="site-header"><div class="container nav-wrap"><a class="brand" href="/" data-route><span class="brand-mark">G</span><span>GlobalBank</span></a><button id="menu-toggle" class="menu-toggle" aria-label="Toggle navigation">☰</button><nav class="site-nav" aria-label="Primary navigation">${primaryLinks.map(path => link(path, routes[path].label, route.label === routes[path].label ? 'active' : '')).join('')}<span class="nav-divider"></span>${link('/login', 'Log in', 'nav-login')}${link('/register', 'Get started', 'button button-small')}</nav></div></header><main id="main-content">${content}</main><footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="/" data-route><span class="brand-mark">G</span><span>GlobalBank</span></a><p class="footer-copy">A digital-first foundation for a more connected financial life.</p></div><div><strong>Explore</strong>${link('/knowledge', 'Knowledge')} ${link('/resources', 'Resources')} ${link('/community', 'Community')}</div><div><strong>Company</strong>${link('/about', 'About')} ${link('/guidelines', 'Guidelines')} ${link('/contact', 'Contact')}</div><div><strong>Account</strong>${link('/login', 'Log in')} ${link('/register', 'Register')}</div></div><div class="container footer-bottom"><span>© <span id="year"></span> GlobalBank. Prototype experience.</span><span>Designed with clarity and care.</span></div></footer>`;
}
function hero(kicker, title, text, actions = '') { return `<section class="hero container"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p class="hero-copy">${text}</p><div class="hero-actions">${actions}</div></section>`; }
function sectionIntro(kicker, title, text) { return `<div class="section-intro"><span class="eyebrow">${kicker}</span><h2>${title}</h2><p>${text}</p></div>`; }
function homePage() { return `${hero('GLOBAL DIGITAL BANKING', 'Banking without borders.', 'One calm, connected place to understand your money, move globally, and plan what comes next.', `${link('/register', 'Explore the experience', 'button')} ${link('/knowledge', 'Learn how it works', 'button button-ghost')}`)}<section class="container signal-grid"><div class="signal-panel"><span class="eyebrow">THE GLOBAL SIGNAL</span><strong>24 / 7</strong><p>Clarity across time zones, currencies, and your next move.</p><div class="signal-line"></div></div><div class="signal-panel"><span class="eyebrow">DESIGNED AROUND YOU</span><strong>01</strong><p>Simple tools and useful knowledge, without the noise.</p><div class="signal-line"></div></div><div class="signal-panel"><span class="eyebrow">BUILT WITH CARE</span><strong>∞</strong><p>A thoughtful foundation for a more inclusive financial future.</p><div class="signal-line"></div></div></section><section class="container content-section">${sectionIntro('A CLEARER SYSTEM', 'Everything in one considered space.', 'Explore a focused set of tools, guides, and experiences designed for people living, working, and thinking globally.')}<div class="feature-grid">${card(icon.globe, 'Global perspective', 'See the context behind every decision with a world of useful information.', link('/knowledge', 'Explore knowledge →'))}${card(icon.chart, 'A clearer dashboard', 'A calm overview for accounts, activity, and the things that matter most.', link('/dashboard', 'Preview dashboard →'))}${card(icon.shield, 'Designed for trust', 'A transparent foundation where safety, clarity, and user control come first.', link('/guidelines', 'Read our guidelines →'))}</div></section>`; }
function knowledgePage() { return `${hero('KNOWLEDGE', 'Knowledge for a global life.', 'Clear explainers and considered perspectives for navigating money across borders.', link('/resources', 'Browse resources', 'button'))}<section class="container content-section"><div class="article-grid">${card('01', 'Moving money internationally', 'What to consider when currencies, fees, timing, and local rules meet.', link('/resources', 'Read guide →'))}${card('02', 'The language of banking', 'A plain-language glossary for the terms that shape your financial choices.', link('/resources', 'Open glossary →'))}${card('03', 'Planning across borders', 'Practical starting points for building confidence wherever life takes you.', link('/contact', 'Talk to us →'))}</div></section>`; }
function communityPage() { return `${hero('COMMUNITY', 'Build a better financial future together.', 'A future-facing space for thoughtful questions, shared learning, and useful ideas.', link('/guidelines', 'View community guidelines', 'button'))}<section class="container content-section"><div class="community-layout"><div class="community-placeholder"><span class="eyebrow">COMING IN A LATER PHASE</span><h2>A considered community space.</h2><p>We are shaping the experience before opening the doors. For now, explore the knowledge and resources designed to help you get oriented.</p><div class="hero-actions">${link('/knowledge', 'Explore knowledge', 'button')} ${link('/contact', 'Share an idea', 'button button-ghost')}</div></div><div class="side-note"><span class="card-icon">${icon.people}</span><h3>Made for useful conversation</h3><p>No noise. No false certainty. Just people sharing what they have learned.</p></div></div></section>`; }
function membershipPage() { return `${hero('MEMBERSHIP', 'A clearer way to manage money.', 'Choose the level of support that fits your journey. Membership details are presented as a preview for this MVP.', '')}<section class="container content-section"><div class="pricing-grid"><div class="price-card"><span class="eyebrow">ESSENTIAL</span><h2>Foundation</h2><p>Simple tools and knowledge for getting oriented.</p><strong>Free</strong><ul><li>Global knowledge library</li><li>Essential resources</li><li>Personal dashboard preview</li></ul>${link('/register', 'Create a profile', 'button button-ghost')}</div><div class="price-card featured"><span class="eyebrow">MOST FLEXIBLE</span><h2>Connected</h2><p>A more complete view for a life that crosses borders.</p><strong>Coming soon</strong><ul><li>Personalized insights</li><li>Expanded global tools</li><li>Priority support experience</li></ul>${link('/contact', 'Join the waitlist', 'button')}</div></div></section>`; }
function resourcesPage() { return `${hero('RESOURCES', 'Practical tools for every move.', 'Useful starting points, thoughtfully organized so you can spend less time searching and more time moving forward.', '')}<section class="container content-section"><div class="resource-list"><a href="/knowledge" data-route><span>GUIDE</span><strong>International banking, explained</strong><em>Start here →</em></a><a href="/dashboard" data-route><span>TOOL</span><strong>Global time-zone dashboard</strong><em>Preview →</em></a><a href="/contact" data-route><span>SUPPORT</span><strong>Questions before you begin?</strong><em>Contact us →</em></a></div></section>`; }
function aboutPage() { return `${hero('ABOUT GLOBALBANK', 'Built for a connected world.', 'GlobalBank is a product direction focused on making global financial experiences feel more understandable, human, and useful.', '')}<section class="container narrow content-section"><h2>Our point of view</h2><p>Financial tools should respect your attention. This prototype brings useful context, calm interfaces, and a global perspective into one place.</p></section>`; }
function guidelinesPage() { return `${hero('GUIDELINES', 'A safer, more useful community.', 'These principles guide how we design experiences and how people should treat one another here.', '')}<section class="container content-section"><div class="guideline-grid"><div><span>01</span><h3>Be constructive</h3><p>Share useful context and leave room for different experiences.</p></div><div><span>02</span><h3>Protect privacy</h3><p>Never share passwords, account numbers, or private personal information.</p></div><div><span>03</span><h3>Stay curious</h3><p>Ask questions, check assumptions, and value clear explanations.</p></div></div></section>`; }
function contactPage() { return `${hero('CONTACT', 'Let’s start a conversation.', 'Have a question about the product direction, resources, or what comes next? We would like to hear from you.', '')}<section class="container narrow content-section"><form class="contact-form" onsubmit="event.preventDefault(); alert('Thanks — this demo form is ready to connect to a service in a later phase.');"><label>Name<input required placeholder="Your name"></label><label>Email<input required type="email" placeholder="you@example.com"></label><label>Message<textarea required rows="5" placeholder="How can we help?"></textarea></label><button type="submit">Send message ${icon.arrow}</button></form></section>`; }
function authPage() { const isLogin = window.location.pathname === '/login'; return `${hero(isLogin ? 'ACCOUNT ACCESS' : 'JOIN THE EXPERIENCE', isLogin ? 'Welcome back.' : 'Start your global journey.', isLogin ? 'This demo login flow is ready for a secure authentication service in a later phase.' : 'Create a prototype profile and explore the direction of GlobalBank.', '')}<section class="container narrow auth-wrap"><form class="auth-form" onsubmit="event.preventDefault(); alert('Authentication is not connected yet. This is a frontend-only prototype.');">${!isLogin ? '<label>Full name<input required placeholder="Your full name"></label>' : ''}<label>Email<input required type="email" placeholder="you@example.com"></label><label>Password<input required type="password" placeholder="••••••••"></label><button type="submit">${isLogin ? 'Log in' : 'Create profile'} ${icon.arrow}</button><p class="muted">${isLogin ? 'New here? ' + link('/register', 'Create a profile') : 'Already have a profile? ' + link('/login', 'Log in')}</p></form></section>`; }
function dashboardPage() { return `${hero('PERSONAL DASHBOARD', 'Your global overview.', 'A calm preview of the place where your accounts, activity, and global tools will come together.', '')}<section class="container dashboard-grid"><div class="dashboard-card balance"><span class="eyebrow">TOTAL BALANCE · DEMO</span><strong>$24,850.72</strong><span class="positive">↑ 4.8% this month</span></div><div class="dashboard-card"><span class="eyebrow">RECENT ACTIVITY</span><div class="activity-row"><span>Salary payment</span><strong class="positive">+$5,200</strong></div><div class="activity-row"><span>International transfer</span><strong>−$850</strong></div><div class="activity-row"><span>Card payment</span><strong>−$42.50</strong></div></div><div class="dashboard-card"><span class="eyebrow">GLOBAL CLOCK</span><div id="dashboard-clock">Loading clocks…</div></div></section><p class="container demo-note">Demo environment — no real accounts, authentication, or money movement are connected.</p>`; }
function updateClocks() { document.querySelectorAll('[data-clock]').forEach(element => element.textContent = new Intl.DateTimeFormat(undefined, { timeZone: element.dataset.clock, hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).format(new Date())); }
function loadClock() { const target = document.querySelector('#dashboard-clock'); if (target) { target.innerHTML = clockZones.map(([name, zone]) => `<div class="clock-row"><span>${name}</span><strong data-clock="${zone}">--:--:--</strong></div>`).join(''); updateClocks(); } }
window.addEventListener('popstate', render); window.addEventListener('load', render); setInterval(updateClocks, 1000);
